---
name: sunset_trigger
pack: astral
description: Sets theatre mode in the media room at sunset.
enabled: true
trigger:
  type: astral.sunset
  ref: astral.sunset
  description: Trigger type for sunset.
action:
  ref: lifx.set_theatre
  description: Sets theatre mode in the media room.
